# To build this:
# docker buildx bake --no-cache --push
# but node16 is an issue on m1 apparently (https://github.com/docker/for-mac/issues/5831)
version: "3.8"

services:
    trello:
        container_name: trellocms
        image: pitilezard/trello-cms:latest
        build:
            context: ..
            dockerfile: docker/Dockerfile
